version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-php-listener
    image: listener/php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
    command: php index.php
  
  nginx:
    image: nginx:latest
    container_name: app-nginx-listener
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge