openapi: 3.0.3
info:
  title: 'Sistema de Agenda de Contatos'
  description: 'O Sistema de Agenda de Contatos é uma aplicação desenvolvida em API, utilizando o framework Laravel, que permite aos usuários autenticados gerenciar seus contatos de forma eficiente. O objetivo é fornecer as operações básicas de criação, leitura, atualização e exclusão (CRUD) para os contatos da agenda.'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000/api'
paths:
  /api/register:
    post:
      summary: 'Registra um novo usuário.'
      operationId: registraUmNovoUsurio
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Nome do usuário.'
                  example: João
                email:
                  type: string
                  description: 'Email do usuário.'
                  example: joao@teste.com
                password:
                  type: string
                  description: 'Senha do usuário.'
                  example: '123456'
              required:
                - name
                - email
                - password
      security: []
  /api/auth/login:
    post:
      summary: 'Faz o login do usuário.'
      operationId: fazOLoginDoUsurio
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Email do usuário.'
                  example: joao@teste.com
                password:
                  type: string
                  description: 'Senha do usuário.'
                  example: '123456'
              required:
                - email
                - password
      security: []
  /api/auth/logout:
    post:
      summary: 'Faz o logout do usuário.'
      operationId: fazOLogoutDoUsurio
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
  /api/auth/refresh:
    post:
      summary: 'Atualiza o token do usuário.'
      operationId: atualizaOTokenDoUsurio
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
  /api/auth/me:
    post:
      summary: 'Retorna os dados do usuário logado.'
      operationId: retornaOsDadosDoUsurioLogado
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
  /api/contacts:
    get:
      summary: 'Busca todos os contatos do usuário logado com paginação.'
      operationId: buscaTodosOsContatosDoUsurioLogadoComPaginao
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {token}'
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
    post:
      summary: 'Insere um novo contato para o usuário logado.'
      operationId: insereUmNovoContatoParaOUsurioLogado
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {token}'
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Nome do contato.'
                  example: João
                second_name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 100 characters.'
                  example: mxtnwvikjppycxfqjdjw
                email:
                  type: string
                  description: 'Email do contato.'
                  example: joaosilva@teste.com
                number:
                  type: string
                  description: 'Número do contato.'
                  example: (11)999999999
                secondName:
                  type: string
                  description: 'Nome do contato.'
                  example: Silva
              required:
                - name
                - email
                - number
  '/api/contacts/{id}':
    get:
      summary: 'Busca um contato do usuário logado.'
      operationId: buscaUmContatoDoUsurioLogado
      description: ''
      parameters:
        -
          in: query
          name: id
          description: 'Id do contato.'
          example: ecd4f3ff-7e8d-4358-ac74-f997955c7c86
          required: true
          schema:
            type: string
            description: 'Id do contato.'
            example: ecd4f3ff-7e8d-4358-ac74-f997955c7c86
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {token}'
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
    put:
      summary: 'Atualiza um contato do usuário logado.'
      operationId: atualizaUmContatoDoUsurioLogado
      description: ''
      parameters:
        -
          in: query
          name: id
          description: 'Id do contato.'
          example: ecd4f3ff-7e8d-4358-ac74-f997955c7c86
          required: true
          schema:
            type: string
            description: 'Id do contato.'
            example: ecd4f3ff-7e8d-4358-ac74-f997955c7c86
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {token}'
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Nome do contato.'
                  example: João
                secondName:
                  type: string
                  description: 'Nome do contato.'
                  example: Silva
                email:
                  type: string
                  description: 'Email do contato.'
                  example: joaosilva@teste.com
                number:
                  type: string
                  description: 'Número do contato.'
                  example: (11)999999999
    delete:
      summary: 'Deleta um contato do usuário logado.'
      operationId: deletaUmContatoDoUsurioLogado
      description: ''
      parameters:
        -
          in: query
          name: id
          description: 'Id do contato.'
          example: ecd4f3ff-7e8d-4358-ac74-f997955c7c86
          required: true
          schema:
            type: string
            description: 'Id do contato.'
            example: ecd4f3ff-7e8d-4358-ac74-f997955c7c86
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {token}'
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the contact.'
        example: dicta
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
