version: '3'

services:

    app:
        build: .
        container_name: user-contacts-app
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - app-network
        depends_on:
            - db

    nginx:
        build: .docker/nginx
        container_name: user-contacts-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        container_name: user-contacts-db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=db
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    localstack:
        image: localstack/localstack
        container_name: user-contacts-localstack
        ports:
            - "4566:4566"
            - "4571:4571"
        environment:
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=fakeAccessKeyId
            - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
            - SERVICES=s3
            - DEBUG=1
            - DEFAULT_REGION=us-east-1
            - HOSTNAME_EXTERNAL=localstack
        volumes:
            - "./.docker/localstack:/docker-entrypoint-initaws.d"
        networks:
            - app-network

networks:
    app-network:
        name: app-network
        driver: bridge