name: Laravel

on:
  push:
    branches: [ "main" ]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Checkout Project Repository
      run: cd user-contacts
    - name: Copy .env
      run: cd user-contacts && php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: cd user-contacts && composer install
    - name: Generate key
      run: cd user-contacts && php artisan key:generate
    - name: Directory Permissions
      run: cd user-contacts && chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        cd user-contacts
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: cd user-contacts && vendor/bin/phpunit